name: Ayden Choi
favicon: null
layout_spectrum: 0.24248
typography_spectrum: 0.50361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5f5258'
    - '#a49695'
    - '#f0eae6'
    - '#9a0011'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
